apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: ecommerce
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS ecommerce_authdb;
    CREATE DATABASE IF NOT EXISTS ecommerce_productdb;
    CREATE DATABASE IF NOT EXISTS ecommerce_inventorydb;
    CREATE DATABASE IF NOT EXISTS ecommerce_orderdb;
    CREATE DATABASE IF NOT EXISTS ecommerce_paymentdb;