spring.application.name=product-service


server.port=8091


spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_productdb
spring.datasource.username=root
spring.datasource.password=yash8252

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true


# Kafka Server
spring.kafka.bootstrap-servers=localhost:9092

# Producer Configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer Configuration
spring.kafka.consumer.group-id=product-service-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Trusted packages for JSON deserialization
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Default topic (optional)
kafka.topic.product-created=product-created-topic


management.endpoints.web.exposure.include=*
management.endpoint.prometheus.enabled=true
management.endpoints.web.base-path=/actuator