apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
    - port: 8092
      targetPort: 8092
      nodePort: 30092