apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: yash8252
  JWT_SECRET: mysupersecurekeyformysafarsaathijwt1234567890abcdefABCDEF1234567890